### PR TITLE
Release 1.5

### PR DESCRIPTION
**Pull request by SoapGentoo**

### CODE REVIEW

**Comment by SoapGentoo** [comment]
@umlaeute

**Comment by umlaeute** [comment]
???

**Review by evpobr — CHANGES_REQUESTED** [review]
Add to NEWS please: Fix spelling mistakes.

**Comment by SoapGentoo** [comment]
@evpobr good now?

**Comment by evpobr** [comment]
> CMake is experimental here. No Windows support.

**Comment by SoapGentoo** [comment]
now?

**Comment by evpobr** [comment]
I didn't want to say that you need to add my entire comment, i apologize. Just add: "Add experimental CMake support". 

After that, I have no suggestions.

**Review by evpobr — APPROVED** [review]

**Comment by SoapGentoo** [comment]
You commented on an outdated commit. Please either specify the **exact** wording or tell me **exactly** what you want me to do.

**Comment by evpobr** [comment]
Ok now.

**Comment by evpobr** [comment]
Thank you.

**Comment by SoapGentoo** [comment]
ok, all done from my side

**Comment by evpobr** [comment]
No Windows releases, CMake project is experrimental.

**Pull request closed without merging**
